### ISSUE TITLE
Missing Components

### ISSUE THREAD

**Issue by CoIorEvent8** [SleepingRian/uswds#1]
This does not seem to include any files related to USWDS right now. I'd recommend moving to a maintained repo.

**Comment by SleepingRian** [comment]
Hey @CoIorEvent8, as mentioned in the readme, this is a work in progress and was moved to this repo to continue development, in which upon completion, it will be moved to a maintained repo. We appreciate your feedback!

**Comment by CoIorEvent8** [comment]
Please archive this, it is not close to being done. 😊

**Comment by SleepingRian** [comment]
It not being close to done, does not disregard it's need for a repo, thank you for your feedback, but this issue is now closed.

**Comment by CoIorEvent8** [comment]
Completed would indicate that the issue is solved, but there is no changes to the REPO thus, it is not actually completed.

I would be happy to make a pull request with new components if you would so kindly assign me this issue. Thanks!

**Comment by SleepingRian** [comment]
I can assign this issue to you, if you can complete the USWDS banner & alert,  it needs to be completely in tailwind, and be responsive for all devices.

**Comment by CoIorEvent8** [comment]
You need to add a license before I even consider contributing.

**Comment by CoIorEvent8** [comment]
Thanks for adding it after I sent my message! Remember, open source software contributions are not required work, and are often done by people in their spare time who wish to maintain software - oftentimes not being paid for doing so. Thus, it is important to remain open to recieving help or this project will go nowhere! (Which is where it is at right now) 🤗
 https://github.com/SleepingRian/uswds/commit/8678d8beaf076cbc79cf05e8fa799bf430329b1d
